window.STUDENT_STUDIES_2024 = [
  {
    "id": "2563318",
    "title": "Assignment 2 - example",
    "student": "Course Example",
    "assignment": "Assignment 2",
    "category": "Course Example",
    "slug": "assignment-2-example",
    "path": "assignment-2-example/",
    "sourcePath": "assignment-2-example/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2563318",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564047",
    "title": "Assignment 1 - Malhar S.",
    "student": "Malhar S",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-malhar-s",
    "path": "assignment-1-malhar-s/",
    "sourcePath": "assignment-1-malhar-s/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564047",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564056",
    "title": "Assignment 1 - example",
    "student": "Course Example",
    "assignment": "Assignment 1",
    "category": "Course Example",
    "slug": "assignment-1-example",
    "path": "assignment-1-example/",
    "sourcePath": "assignment-1-example/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564056",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564084",
    "title": "Assignment 1 - Alina S.",
    "student": "Alina S",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-alina-s",
    "path": "assignment-1-alina-s/",
    "sourcePath": "assignment-1-alina-s/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564084",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564116",
    "title": "Assignment 1 - Anna L.",
    "student": "Anna L",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-anna-l",
    "path": "assignment-1-anna-l/",
    "sourcePath": "assignment-1-anna-l/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564116",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564121",
    "title": "Assignment 1 - Elias N.",
    "student": "Elias N",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-elias-n",
    "path": "assignment-1-elias-n/",
    "sourcePath": "assignment-1-elias-n/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564121",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564124",
    "title": "Assignment 1 - Flynn D.",
    "student": "Flynn D",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-flynn-d",
    "path": "assignment-1-flynn-d/",
    "sourcePath": "assignment-1-flynn-d/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564124",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564148",
    "title": "Assignment 1 - Kaius K.",
    "student": "Kaius K",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-kaius-k",
    "path": "assignment-1-kaius-k/",
    "sourcePath": "assignment-1-kaius-k/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564148",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564161",
    "title": "Assignment 1 - Rosa H.",
    "student": "Rosa H",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-rosa-h",
    "path": "assignment-1-rosa-h/",
    "sourcePath": "assignment-1-rosa-h/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564161",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564165",
    "title": "Assignment 1 - Tuomas H.",
    "student": "Tuomas H",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-tuomas-h",
    "path": "assignment-1-tuomas-h/",
    "sourcePath": "assignment-1-tuomas-h/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564165",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564174",
    "title": "Assignment 1 - Vibe T.",
    "student": "Vibe T",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-vibe-t",
    "path": "assignment-1-vibe-t/",
    "sourcePath": "assignment-1-vibe-t/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564174",
    "license": "See original OpenProcessing page",
    "instructions": "",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564184",
    "title": "Assignment 1 - Yuying J.",
    "student": "Yuying J",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-yuying-j",
    "path": "assignment-1-yuying-j/",
    "sourcePath": "assignment-1-yuying-j/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564184",
    "license": "See original OpenProcessing page",
    "instructions": "",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2564996",
    "title": "Assignment 1 - Martina L.",
    "student": "Martina L",
    "assignment": "Assignment 1",
    "category": "Student Work",
    "slug": "assignment-1-martina-l",
    "path": "assignment-1-martina-l/",
    "sourcePath": "assignment-1-martina-l/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2564996",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2582351",
    "title": "Assignment 2 - Alina",
    "student": "Alina",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-alina",
    "path": "assignment-2-alina/",
    "sourcePath": "assignment-2-alina/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2582351",
    "license": "See original OpenProcessing page",
    "instructions": "no interaction",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2582358",
    "title": "Assignment 2 - Anna",
    "student": "Anna",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-anna",
    "path": "assignment-2-anna/",
    "sourcePath": "assignment-2-anna/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2582358",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2582361",
    "title": "Assignment 2 - Elias",
    "student": "Elias",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-elias",
    "path": "assignment-2-elias/",
    "sourcePath": "assignment-2-elias/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2582361",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2582366",
    "title": "Assignment 2 - Flynn",
    "student": "Flynn",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-flynn",
    "path": "assignment-2-flynn/",
    "sourcePath": "assignment-2-flynn/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2582366",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2582368",
    "title": "Assignment 2 - Kaius",
    "student": "Kaius",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-kaius",
    "path": "assignment-2-kaius/",
    "sourcePath": "assignment-2-kaius/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2582368",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2582371",
    "title": "Assignment 2 - Malhar",
    "student": "Malhar",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-malhar",
    "path": "assignment-2-malhar/",
    "sourcePath": "assignment-2-malhar/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2582371",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2582375",
    "title": "Assignment 2 - Martina",
    "student": "Martina",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-martina",
    "path": "assignment-2-martina/",
    "sourcePath": "assignment-2-martina/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2582375",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594098",
    "title": "Assignment 2 - example",
    "student": "Course Example",
    "assignment": "Assignment 2",
    "category": "Course Example",
    "slug": "assignment-2-example-2594098",
    "path": "assignment-2-example-2594098/",
    "sourcePath": "assignment-2-example-2594098/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594098",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594102",
    "title": "Assignment 2 - Rosa",
    "student": "Rosa",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-rosa",
    "path": "assignment-2-rosa/",
    "sourcePath": "assignment-2-rosa/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594102",
    "license": "See original OpenProcessing page",
    "instructions": "mouse click",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594103",
    "title": "Assignment 2 - Tuomas",
    "student": "Tuomas",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-tuomas",
    "path": "assignment-2-tuomas/",
    "sourcePath": "assignment-2-tuomas/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594103",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594110",
    "title": "Assignment 2 - Vibe",
    "student": "Vibe",
    "assignment": "Assignment 2",
    "category": "Student Work",
    "slug": "assignment-2-vibe",
    "path": "assignment-2-vibe/",
    "sourcePath": "assignment-2-vibe/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594110",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594119",
    "title": "Assignment 3 - example",
    "student": "Course Example",
    "assignment": "Assignment 3",
    "category": "Course Example",
    "slug": "assignment-3-example",
    "path": "assignment-3-example/",
    "sourcePath": "assignment-3-example/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594119",
    "license": "See original OpenProcessing page",
    "instructions": "generating new ones at every play",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594121",
    "title": "Assignment 3 - Alina",
    "student": "Alina",
    "assignment": "Assignment 3",
    "category": "Student Work",
    "slug": "assignment-3-alina",
    "path": "assignment-3-alina/",
    "sourcePath": "assignment-3-alina/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594121",
    "license": "See original OpenProcessing page",
    "instructions": "press with mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594125",
    "title": "Assignment 3 - Anna",
    "student": "Anna",
    "assignment": "Assignment 3",
    "category": "Student Work",
    "slug": "assignment-3-anna",
    "path": "assignment-3-anna/",
    "sourcePath": "assignment-3-anna/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594125",
    "license": "See original OpenProcessing page",
    "instructions": "",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594129",
    "title": "Assignment 3 - Elias",
    "student": "Elias",
    "assignment": "Assignment 3",
    "category": "Student Work",
    "slug": "assignment-3-elias",
    "path": "assignment-3-elias/",
    "sourcePath": "assignment-3-elias/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594129",
    "license": "See original OpenProcessing page",
    "instructions": "mouse press",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594134",
    "title": "Assignment 3 - Flynn",
    "student": "Flynn",
    "assignment": "Assignment 3",
    "category": "Student Work",
    "slug": "assignment-3-flynn",
    "path": "assignment-3-flynn/",
    "sourcePath": "assignment-3-flynn/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594134",
    "license": "See original OpenProcessing page",
    "instructions": "mouse",
    "fileCount": 1,
    "mode": "pjs"
  },
  {
    "id": "2594141",
    "title": "Assignment 3 - Kaius",
    "student": "Kaius",
    "assignment": "Assignment 3",
    "category": "Student Work",
    "slug": "assignment-3-kaius",
    "path": "assignment-3-kaius/",
    "sourcePath": "assignment-3-kaius/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2594141",
    "license": "See original OpenProcessing page",
    "instructions": "",
    "fileCount": 1,
    "mode": "pjs"
  }
];
