// Source of truth for the 2025-2026 year page.
// assets/year.js renders session cards, sketch cards, slide controls, and search
// from this data. Update this file before editing repeated markup by hand, then
// run npm run build:index and npm run check.
window.COURSE_DATA = {
  year: "2025-2026",
  currentSession: {
    id: "session-06",
    description: "Session 06 includes arrays, objects, particle systems, and motion fields.",
    links: [
      { label: "Open Session 06", href: "sessions/session-06/", primary: true },
      { label: "Read Session 06 slides", href: "#slides", pdf: "slides/session-06.pdf", title: "Session 06 - Arrays, objects, and particles" },
      { label: "Run particles follow", href: "web/particles-follow/" },
    ],
  },
  sessions: [
    {
      id: "session-01",
      kicker: "Session 01",
      title: "Drawing, coordinates, and first functions",
      description: "Shapes, color, canvas coordinates, and reusable drawing code.",
      duration: "2h 45m",
      tags: ["drawing", "coordinates", "functions"],
      href: "sessions/session-01/",
      links: [
        { label: "Open session page", href: "sessions/session-01/", primary: true },
        { label: "Open web sketch", href: "web/face-exercise/" },
        { label: "Read slides here", href: "#slides", pdf: "slides/session-01.pdf", title: "Session 01 - Drawing, coordinates, and first functions" },
      ],
    },
    {
      id: "session-02",
      kicker: "Session 02",
      title: "Mouse input and changing color",
      description: "Mouse position, clicks, mapping values, and dynamic color.",
      duration: "2h 45m",
      tags: ["mouse", "variables", "interaction"],
      href: "sessions/session-02/",
      links: [
        { label: "Open session page", href: "sessions/session-02/", primary: true },
        { label: "Open web sketch", href: "web/mouse-shapes/" },
        { label: "Read slides here", href: "#slides", pdf: "slides/session-02.pdf", title: "Session 02 - Mouse input and changing color" },
      ],
    },
    {
      id: "session-03",
      kicker: "Session 03",
      title: "Conditionals, loops, and movement",
      description: "Decision-making, repeated actions, frame-based motion, and state.",
      duration: "2h 45m",
      tags: ["conditionals", "loops", "motion"],
      href: "sessions/session-03/",
      links: [
        { label: "Open session page", href: "sessions/session-03/", primary: true },
        { label: "Open hover sketch", href: "web/hover-grid/" },
        { label: "Open ball sketch", href: "web/bouncing-ball/" },
        { label: "Read slides here", href: "#slides", pdf: "slides/session-03.pdf", title: "Session 03 - Conditionals, loops, and movement" },
      ],
    },
    {
      id: "session-04",
      kicker: "Session 04",
      title: "Waves, grids, noise, and recursion",
      description: "Nested loops, sine waves, random walks, Perlin noise, and recursion.",
      duration: "2h 45m",
      tags: ["loops", "noise", "recursion"],
      href: "sessions/session-04/",
      links: [
        { label: "Open session page", href: "sessions/session-04/", primary: true },
        { label: "Open waves sketch", href: "web/simple-waves/" },
        { label: "Open grid sketch", href: "web/generative-grid/" },
        { label: "Read slides here", href: "#slides", pdf: "slides/session-04.pdf", title: "Session 04 - Waves, grids, noise, and recursion" },
      ],
    },
    {
      id: "session-05",
      kicker: "Session 05",
      title: "Functions, parameters, and reuse",
      description: "Named behavior, parameterized drawing, randomness, and recursion.",
      duration: "2h 45m",
      tags: ["functions", "parameters", "recursion"],
      href: "sessions/session-05/",
      links: [
        { label: "Open session page", href: "sessions/session-05/", primary: true },
        { label: "Open shapes sketch", href: "web/shapes-function/" },
        { label: "Open spiral sketch", href: "web/spiral-spins/" },
        { label: "Read slides here", href: "#slides", pdf: "slides/session-05.pdf", title: "Session 05 - Functions, parameters, and reuse" },
      ],
    },
    {
      id: "session-06",
      kicker: "Session 06",
      title: "Arrays, objects, and particles",
      description: "Object-oriented thinking, arrays, particle systems, and smooth motion fields.",
      duration: "2h 45m",
      tags: ["arrays", "objects", "particles"],
      href: "sessions/session-06/",
      links: [
        { label: "Open session page", href: "sessions/session-06/", primary: true },
        { label: "Open follow sketch", href: "web/particles-follow/" },
        { label: "Open noise sketch", href: "web/particles-noise/" },
        { label: "Read slides here", href: "#slides", pdf: "slides/session-06.pdf", title: "Session 06 - Arrays, objects, and particles" },
      ],
    },
  ],
  sketches: [
    {
      id: "face-exercise",
      title: "Face Exercise",
      session: "Session 01",
      page: "web/face-exercise/index.html",
      source: "source/session-01/face_exercise/face_exercise.pde",
      description: "Use this to see how simple shapes become a reusable drawFace() function.",
      try: "change face size, eye spacing, mouth arc, or call drawFace() more than once.",
      tags: ["functions", "drawing"],
      difficulty: "intro",
      related: ["mouse-shapes"],
    },
    {
      id: "mouse-shapes",
      title: "Mouse Shapes",
      session: "Session 02",
      page: "web/mouse-shapes/index.html",
      source: "source/session-02/mouseshapes/mouseshapes.pde",
      description: "Move the pointer to control a circle, an opposite-position square, and the background color.",
      try: "swap the opposite movement, change the color mappings, or alter shape sizes.",
      tags: ["mouseX", "map()", "interaction"],
      difficulty: "intro",
      related: ["hover-grid", "bouncing-ball"],
    },
    {
      id: "hover-grid",
      title: "Hover Grid",
      session: "Session 03",
      page: "web/hover-grid/index.html",
      source: "source/session-03/hoverisred/hoverisred.pde",
      description: "Move across an 8 by 8 grid to see how conditionals react to pointer position.",
      try: "change rows and columns, use gradients, or make neighboring cells react too.",
      tags: ["conditionals", "loops"],
      difficulty: "intro",
      related: ["generative-grid"],
    },
    {
      id: "bouncing-ball",
      title: "Bouncing Ball Color",
      session: "Session 03",
      page: "web/bouncing-ball/index.html",
      source: "source/session-03/extra_bouncingballcolor/extra_bouncingballcolor.pde",
      description: "Watch a ball reverse at the canvas edges and change color on each bounce.",
      try: "adjust speed, radius, background fade, or add more bouncing objects.",
      tags: ["motion", "state"],
      difficulty: "intro",
      related: ["particles-follow"],
    },
    {
      id: "simple-waves",
      title: "Simple Waves",
      session: "Session 04",
      page: "web/simple-waves/index.html",
      source: "source/session-04/extra_simplewaves/extra_simplewaves.pde",
      description: "Use an animated sine wave to see how time changes repeated drawing.",
      try: "change amplitude, frequency, spacing, or draw connected lines instead of points.",
      tags: ["sin()", "animation"],
      difficulty: "medium",
      related: ["generative-grid", "spiral-spins"],
    },
    {
      id: "generative-grid",
      title: "Generative Grid",
      session: "Session 04",
      page: "web/generative-grid/index.html",
      source: "source/session-04/generativegrid/generativegrid.pde",
      description: "Use a rotating noise-driven grid to connect nested loops with smooth randomness.",
      try: "change grid size, rotation amount, tile shape, or noise scale.",
      tags: ["noise()", "nested loops"],
      difficulty: "medium",
      related: ["hover-grid", "particles-noise"],
    },
    {
      id: "shapes-function",
      title: "Shapes Function",
      session: "Session 05",
      page: "web/shapes-function/index.html",
      source: "source/session-05/shapesfunction/shapesfunction.pde",
      description: "Click to regenerate a composition made from one reusable abstract-shape function.",
      try: "click the sketch to regenerate, add a fourth shape type, or constrain the color palette.",
      tags: ["parameters", "randomness"],
      difficulty: "medium",
      related: ["spiral-spins"],
    },
    {
      id: "spiral-spins",
      title: "Spiral Spins",
      session: "Session 05",
      page: "web/spiral-spins/index.html",
      source: "source/session-05/extra_spiralspins/extra_spiralspins.pde",
      description: "Move the pointer to control a polar-coordinate spiral's speed and radius.",
      try: "move the pointer, press T for trails, then change turns, curve, or color mode.",
      tags: ["functions", "polar coordinates"],
      difficulty: "medium",
      related: ["simple-waves"],
    },
    {
      id: "particles-follow",
      title: "Particles Follow",
      session: "Session 06",
      page: "web/particles-follow/index.html",
      source: "source/session-06/particlesfollow/particlesfollow.pde",
      description: "Move the pointer to emit fading particles and see how arrays of objects behave.",
      try: "move the pointer, change lifespan, vary velocity, or color particles by age.",
      tags: ["arrays", "objects"],
      difficulty: "advanced",
      related: ["particles-noise", "bouncing-ball"],
    },
    {
      id: "particles-noise",
      title: "Particles with Noise",
      session: "Session 06",
      page: "web/particles-noise/index.html",
      source: "source/session-06/extra_particles_perlin_noise/extra_particles_perlin_noise.pde",
      description: "Watch particles follow a smooth Perlin-noise field and wrap around the canvas.",
      try: "change particle count, movement speed, fade amount, or noise scale.",
      tags: ["noise()", "systems"],
      difficulty: "advanced",
      related: ["particles-follow", "generative-grid"],
    },
  ],
  slides: [
    { kicker: "Session 01", title: "Session 01 - Drawing, coordinates, and first functions", pdf: "slides/session-01.pdf", tags: ["drawing", "functions"] },
    { kicker: "Session 02", title: "Session 02 - Mouse input and changing color", pdf: "slides/session-02.pdf", tags: ["mouse", "variables"] },
    { kicker: "Session 03", title: "Session 03 - Conditionals, loops, and movement", pdf: "slides/session-03.pdf", tags: ["conditionals", "loops"] },
    { kicker: "Session 04", title: "Session 04 - Waves, grids, noise, and recursion", pdf: "slides/session-04.pdf", tags: ["waves", "noise"] },
    { kicker: "Session 05", title: "Session 05 - Functions, parameters, and reuse", pdf: "slides/session-05.pdf", tags: ["functions", "recursion"] },
    { kicker: "Session 06", title: "Session 06 - Arrays, objects, and particles", pdf: "slides/session-06.pdf", tags: ["arrays", "particles"] },
  ],
  searchExtras: [],
};
