// Source of truth for the 2024-2025 year page. Update this file before editing
// repeated session, sketch, slide, search, duration, difficulty, or related-link
// markup by hand.
window.COURSE_DATA = {
  year: "2024-2025",
  currentSession: {
    id: "session-08",
    description: "Session 08 includes sound, webcam, image-to-sound experiments, and source-first media examples.",
    links: [
      { label: "Open Session 08", href: "sessions/session-08/", primary: true },
      { label: "Read Session 08 slides", href: "#slides", pdf: "slides/session-08.pdf", title: "Session 08 - Sound and camera" },
      { label: "Open webcam mosaic source", href: "source/session-08/extra_webcammosaic/extra_webcammosaic.pde" },
    ],
  },
  sessions: [
    { id: "session-01", kicker: "Session 01", title: "Drawing basics", description: "Coordinates, shapes, color, and first reusable drawing functions.", duration: "2h 45m", tags: ["drawing", "coordinates", "functions"], href: "sessions/session-01/", links: [{ label: "Open session page", href: "sessions/session-01/", primary: true }, { label: "Open smile face", href: "web/smile-face/" }, { label: "Read slides here", href: "#slides", pdf: "slides/session-01.pdf", title: "Session 01 - Drawing basics" }] },
    { id: "session-02", kicker: "Session 02", title: "Mouse and variables", description: "Mouse input, values, operators, and color changes.", duration: "2h 45m", tags: ["mouse", "variables", "interaction"], href: "sessions/session-02/", links: [{ label: "Open session page", href: "sessions/session-02/", primary: true }, { label: "Open mouse shapes", href: "web/mouse-shapes/" }, { label: "Read slides here", href: "#slides", pdf: "slides/session-02.pdf", title: "Session 02 - Mouse and variables" }] },
    { id: "session-03", kicker: "Session 03", title: "Conditionals and movement", description: "Hover states, collisions, changing color, and motion over time.", duration: "2h 45m", tags: ["conditionals", "motion", "state"], href: "sessions/session-03/", links: [{ label: "Open session page", href: "sessions/session-03/", primary: true }, { label: "Open ball sketch", href: "web/bouncing-ball/" }, { label: "Read slides here", href: "#slides", pdf: "slides/session-03.pdf", title: "Session 03 - Conditionals and movement" }] },
    { id: "session-04", kicker: "Session 04", title: "Loops, grids, and waves", description: "Nested loops, repeated structures, waves, and generative grids.", duration: "2h 45m", tags: ["loops", "grids", "waves"], href: "sessions/session-04/", links: [{ label: "Open session page", href: "sessions/session-04/", primary: true }, { label: "Open grid sketch", href: "web/generative-grid/" }, { label: "Read slides here", href: "#slides", pdf: "slides/session-04.pdf", title: "Session 04 - Loops, grids, and waves" }] },
    { id: "session-05", kicker: "Session 05", title: "Functions and recursion", description: "Reusable code, recursive drawing, spiral systems, and noise.", duration: "2h 45m", tags: ["functions", "recursion", "noise"], href: "sessions/session-05/", links: [{ label: "Open session page", href: "sessions/session-05/", primary: true }, { label: "Open tree sketch", href: "web/recursive-tree/" }, { label: "Read slides here", href: "#slides", pdf: "slides/session-05.pdf", title: "Session 05 - Functions and recursion" }] },
    { id: "session-06", kicker: "Session 06", title: "Objects and particles", description: "Object-oriented thinking, arrays, particle systems, and repeated motion.", duration: "2h 45m", tags: ["objects", "arrays", "particles"], href: "sessions/session-06/", links: [{ label: "Open session page", href: "sessions/session-06/", primary: true }, { label: "Open sparkles", href: "web/sparkles/" }, { label: "Read slides here", href: "#slides", pdf: "slides/session-06.pdf", title: "Session 06 - Objects and particles" }] },
    { id: "session-07", kicker: "Session 07", title: "Image and video", description: "Image filters, video filters, glitch effects, and zoom interactions.", duration: "2h 45m", tags: ["image", "video", "pixels"], href: "sessions/session-07/", links: [{ label: "Open session page", href: "sessions/session-07/", primary: true }, { label: "Open video filters", href: "web/video-filters/" }, { label: "Read slides here", href: "#slides", pdf: "slides/session-07.pdf", title: "Session 07 - Image and video" }] },
    { id: "session-08", kicker: "Session 08", title: "Sound and camera", description: "Audio, webcam, image-to-sound, kaleidoscopes, and media experiments.", duration: "2h 45m", tags: ["sound", "camera", "media"], href: "sessions/session-08/", links: [{ label: "Open session page", href: "sessions/session-08/", primary: true }, { label: "Read slides here", href: "#slides", pdf: "slides/session-08.pdf", title: "Session 08 - Sound and camera" }] },
  ],
  sketches: [
    { id: "smile-face", title: "Smile Face", session: "Session 01", page: "web/smile-face/", source: "source/session-01/smileface/smileface.pde", description: "See how one drawing function can produce several related faces.", try: "change proportions, draw more faces, or alter the expression.", tags: ["functions", "drawing"], difficulty: "intro", related: ["follow-mouse"] },
    { id: "follow-mouse", title: "Follow the Mouse", session: "Session 01", page: "web/follow-mouse/", source: "source/session-01/extra_followthemouse/extra_followthemouse.pde", description: "Move the pointer and compare direct input with eased motion.", try: "change the easing value, trail opacity, or follower size.", tags: ["mouse", "motion"], difficulty: "intro", related: ["mouse-shapes"] },
    { id: "mouse-shapes", title: "Mouse Shapes", session: "Session 02", page: "web/mouse-shapes/", source: "source/session-02/mouseshapes/mouseshapes.pde", description: "Use the pointer to control a shape while another removed copys it.", try: "change color mappings, shape size, or removed copyed movement.", tags: ["mouseX", "mapping"], difficulty: "intro", related: ["color-house", "bouncing-ball"] },
    { id: "color-house", title: "Color House", session: "Session 02", page: "web/color-house/", source: "source/session-02/extra_coloronmousepress/extra_coloronmousepress.pde", description: "Click to recolor a simple scene and see mouse events change state.", try: "add windows, change the palette rules, or animate the sky.", tags: ["mousePressed()", "state"], difficulty: "intro", related: ["mouse-shapes"] },
    { id: "bouncing-ball", title: "Bouncing Ball Color", session: "Session 03", page: "web/bouncing-ball/", source: "source/session-03/extra_bouncingballcolor/extra_bouncingballcolor.pde", description: "Watch a ball reverse at the canvas edges and change color on contact.", try: "change speed, radius, color rules, or add more balls.", tags: ["conditionals", "movement"], difficulty: "intro", related: ["sparkles"] },
    { id: "generative-grid", title: "Generative Grid Hover", session: "Session 04", page: "web/generative-grid/", source: "source/session-04/generativegridhover/generativegridhover.pde", description: "Move across nested squares driven by distance, noise, and loops.", try: "change grid density, opacity, rotation, or color mapping.", tags: ["nested loops", "noise()"], difficulty: "medium", related: ["recursive-tree"] },
    { id: "recursive-tree", title: "Recursive Tree", session: "Session 05", page: "web/recursive-tree/", source: "source/session-05/extra_recursivetreeanimated/extra_recursivetreeanimated.pde", description: "Watch a function call itself to grow two removed copyed branching systems.", try: "change branch length, angle, scale, or colors.", tags: ["recursion", "animation"], difficulty: "medium", related: ["generative-grid"] },
    { id: "sparkles", title: "Sparkles", session: "Session 06", page: "web/sparkles/", source: "source/session-06/sparkles/sparkles.pde", description: "See arrays of particle systems emit, update, fade, and remove particles.", try: "change lifespan, velocity, particle size, or color.", tags: ["objects", "arrays"], difficulty: "advanced", related: ["bouncing-ball"] },
    { id: "video-filters", title: "Video Filters", session: "Session 07", page: "web/video-filters/", source: "source/session-07/example_videofilters/example_videofilters.pde", description: "Use a local video file to test image-processing filters without opening a new site.", try: "press I, G, B, or T to toggle filters, then change the pixel rules.", tags: ["video", "pixels"], difficulty: "advanced", related: [] },
  ],
  slides: [
    { kicker: "Session 01", title: "Session 01 - Drawing basics", pdf: "slides/session-01.pdf", tags: ["drawing"] },
    { kicker: "Session 02", title: "Session 02 - Mouse and variables", pdf: "slides/session-02.pdf", tags: ["mouse"] },
    { kicker: "Session 03", title: "Session 03 - Conditionals and movement", pdf: "slides/session-03.pdf", tags: ["conditionals"] },
    { kicker: "Session 04", title: "Session 04 - Loops, grids, and waves", pdf: "slides/session-04.pdf", tags: ["loops"] },
    { kicker: "Session 05", title: "Session 05 - Functions and recursion", pdf: "slides/session-05.pdf", tags: ["functions"] },
    { kicker: "Session 06", title: "Session 06 - Objects and particles", pdf: "slides/session-06.pdf", tags: ["objects"] },
    { kicker: "Session 07", title: "Session 07 - Image and video", pdf: "slides/session-07.pdf", tags: ["image", "video"] },
    { kicker: "Session 08", title: "Session 08 - Sound and camera", pdf: "slides/session-08.pdf", tags: ["sound", "camera"] },
  ],
  searchExtras: [
    { type: "coursework", title: "Assignment 1 Example", href: "source/assignments/coursework1_interaction_example.pde", description: "Course example for an interactive coursework.", keywords: "coursework assignment 1 interaction mouse example" },
    { type: "coursework", title: "Assignment 2 Example", href: "source/assignments/coursework2_generative_grid_example.pde", description: "Course example for a generative grid coursework.", keywords: "coursework assignment 2 generative loops grid example" },
    { type: "coursework", title: "Removed coursework Coursework listing", href: "case-coursework/", description: "Previous-year removed coursework removed copyed into the course site.", keywords: "removed coursework coursework listing removed-source-host reference" },
  ],
};
