window.STUDENT_STUDIES = [
  {
    "id": "2901354",
    "title": "Study 1 - Chrystalla",
    "student": "Chrystalla",
    "study": "Study 1",
    "slug": "study-1-chrystalla",
    "path": "study-1-chrystalla/",
    "sourcePath": "study-1-chrystalla/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901354",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901255",
    "title": "Study 1 - Ella",
    "student": "Ella",
    "study": "Study 1",
    "slug": "study-1-ella",
    "path": "study-1-ella/",
    "sourcePath": "study-1-ella/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901255",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901277",
    "title": "Study 1 - Iuliana",
    "student": "Iuliana",
    "study": "Study 1",
    "slug": "study-1-iuliana",
    "path": "study-1-iuliana/",
    "sourcePath": "study-1-iuliana/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901277",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse + keyboard",
    "fileCount": 1
  },
  {
    "id": "2901315",
    "title": "Study 1 - Jan",
    "student": "Jan",
    "study": "Study 1",
    "slug": "study-1-jan",
    "path": "study-1-jan/",
    "sourcePath": "study-1-jan/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901315",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901352",
    "title": "Study 1 - Jenn",
    "student": "Jenn",
    "study": "Study 1",
    "slug": "study-1-jenn",
    "path": "study-1-jenn/",
    "sourcePath": "study-1-jenn/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901352",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse + keyboard",
    "fileCount": 1
  },
  {
    "id": "2901328",
    "title": "Study 1 - Marton",
    "student": "Marton",
    "study": "Study 1",
    "slug": "study-1-marton",
    "path": "study-1-marton/",
    "sourcePath": "study-1-marton/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901328",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "",
    "fileCount": 1
  },
  {
    "id": "2901307",
    "title": "Study 1 - Matleena",
    "student": "Matleena",
    "study": "Study 1",
    "slug": "study-1-matleena",
    "path": "study-1-matleena/",
    "sourcePath": "study-1-matleena/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901307",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901340",
    "title": "Study 1 - Natalija",
    "student": "Natalija",
    "study": "Study 1",
    "slug": "study-1-natalija",
    "path": "study-1-natalija/",
    "sourcePath": "study-1-natalija/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901340",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse + keyboard",
    "fileCount": 1
  },
  {
    "id": "2901299",
    "title": "Study 1 - Zhenzhen",
    "student": "Zhenzhen",
    "study": "Study 1",
    "slug": "study-1-zhenzhen",
    "path": "study-1-zhenzhen/",
    "sourcePath": "study-1-zhenzhen/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901299",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901342",
    "title": "Study 1 - Zoe",
    "student": "Zoe",
    "study": "Study 1",
    "slug": "study-1-zoe",
    "path": "study-1-zoe/",
    "sourcePath": "study-1-zoe/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901342",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901349",
    "title": "Study 1 - Zunshe",
    "student": "Zunshe",
    "study": "Study 1",
    "slug": "study-1-zunshe",
    "path": "study-1-zunshe/",
    "sourcePath": "study-1-zunshe/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901349",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901398",
    "title": "Study 2 - Chrystalla",
    "student": "Chrystalla",
    "study": "Study 2",
    "slug": "study-2-chrystalla",
    "path": "study-2-chrystalla/",
    "sourcePath": "study-2-chrystalla/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901398",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901361",
    "title": "Study 2 - Ella",
    "student": "Ella",
    "study": "Study 2",
    "slug": "study-2-ella",
    "path": "study-2-ella/",
    "sourcePath": "study-2-ella/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901361",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901366",
    "title": "Study 2 - Iuliana",
    "student": "Iuliana",
    "study": "Study 2",
    "slug": "study-2-iuliana",
    "path": "study-2-iuliana/",
    "sourcePath": "study-2-iuliana/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901366",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901380",
    "title": "Study 2 - Jan",
    "student": "Jan",
    "study": "Study 2",
    "slug": "study-2-jan",
    "path": "study-2-jan/",
    "sourcePath": "study-2-jan/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901380",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901397",
    "title": "Study 2 - Jenn",
    "student": "Jenn",
    "study": "Study 2",
    "slug": "study-2-jenn",
    "path": "study-2-jenn/",
    "sourcePath": "study-2-jenn/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901397",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "",
    "fileCount": 1
  },
  {
    "id": "2901385",
    "title": "Study 2 - Marton",
    "student": "Marton",
    "study": "Study 2",
    "slug": "study-2-marton",
    "path": "study-2-marton/",
    "sourcePath": "study-2-marton/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901385",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "",
    "fileCount": 1
  },
  {
    "id": "2901376",
    "title": "Study 2 - Matleena",
    "student": "Matleena",
    "study": "Study 2",
    "slug": "study-2-matleena",
    "path": "study-2-matleena/",
    "sourcePath": "study-2-matleena/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901376",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 1
  },
  {
    "id": "2901387",
    "title": "Study 2 - Natalija",
    "student": "Natalija",
    "study": "Study 2",
    "slug": "study-2-natalija",
    "path": "study-2-natalija/",
    "sourcePath": "study-2-natalija/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901387",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "",
    "fileCount": 1
  },
  {
    "id": "2901374",
    "title": "Study 2 - Zhenzhen",
    "student": "Zhenzhen",
    "study": "Study 2",
    "slug": "study-2-zhenzhen",
    "path": "study-2-zhenzhen/",
    "sourcePath": "study-2-zhenzhen/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901374",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "mouse",
    "fileCount": 3
  },
  {
    "id": "2901389",
    "title": "Study 2 - Zoe",
    "student": "Zoe",
    "study": "Study 2",
    "slug": "study-2-zoe",
    "path": "study-2-zoe/",
    "sourcePath": "study-2-zoe/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901389",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "",
    "fileCount": 1
  },
  {
    "id": "2901394",
    "title": "Study 2 - Zunshe",
    "student": "Zunshe",
    "study": "Study 2",
    "slug": "study-2-zunshe",
    "path": "study-2-zunshe/",
    "sourcePath": "study-2-zunshe/source.txt",
    "originalUrl": "https://openprocessing.org/sketch/2901394",
    "license": "CC BY-NC-SA 3.0",
    "instructions": "",
    "fileCount": 1
  }
];
